<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Frent" Version="0.8.0-beta" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="NetCord" Version="1.0.0-beta.22" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.22" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.22" />
    <PackageReference Include="NetCord.Services" Version="1.0.0-beta.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Project\CS\Ecs.Loop.Frent\src\Ecs.Loop.Frent.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Greet.Adapter.NetCord\src\Greet.Adapter.NetCord.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Greet.System.Frent\src\Greet.System.Frent.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Ping.Adapter.NetCord\src\Ping.Adapter.NetCord.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Ping.System.Frent\src\Ping.System.Frent.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Ticket.Adapter.Cloudflare\src\Ticket.Adapter.Cloudflare.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Ticket.Adapter.Npgsql\src\Ticket.Adapter.Npgsql.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Ticket.Adapter.NetCord\src\Ticket.Adapter.NetCord.csproj" />
    <ProjectReference Include="..\..\..\Project\CS\Ticket.System.Frent\src\Ticket.System.Frent.csproj" />
  </ItemGroup>

</Project>
